<?php

namespace App\Console\Commands;

use App\Exports\AnalyticsDatasetExport;
use App\Models\ReportSchedule;
use App\Services\AnalyticsService;
use App\Services\NotificationService;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;

/**
 * Milestone 3 (Report Center, Task #65). Generates every due
 * ReportSchedule's file into storage/app/reports and notifies the
 * owning user through the Notification Center -- deliberately NOT an
 * email dispatcher: no Mail transport is configured anywhere in this
 * app today (see docs/ADR/020-report-center.md), so building an email
 * pipeline here would be exactly the kind of unverifiable "looks done,
 * isn't" feature CLAUDE.md warns against. The notification links back
 * into Report Center, where the same dataset can be re-downloaded live
 * at any time -- the stored file is a point-in-time snapshot, not the
 * only way to get the data.
 */
class DispatchScheduledReports extends Command
{
    protected $signature = 'reports:dispatch-scheduled';

    protected $description = 'Generate every due ReportSchedule and notify its owner.';

    public function handle(AnalyticsService $analytics, NotificationService $notifications): int
    {
        $due = ReportSchedule::where('is_active', true)
            ->where(function ($q) {
                $q->whereNull('next_run_at')->orWhere('next_run_at', '<=', now());
            })
            ->with('user')
            ->get();

        $count = 0;

        foreach ($due as $schedule) {
            if (! $schedule->user) {
                continue;
            }

            $dataset = $analytics->dataset($schedule->dataset_key);
            $path = $this->generate($schedule, $dataset);

            $notifications->notify(
                $schedule->user,
                \App\Models\Notification::CATEGORY_INFORMATION,
                "Scheduled report ready: {$dataset['label']}",
                'Generated by Report Center ('.$schedule->frequency.', '.$schedule->format.').',
                route('report-center.index'),
                $schedule
            );

            $schedule->update([
                'last_run_at' => now(),
                'next_run_at' => $schedule->computeNextRunAt(),
            ]);

            $count++;
        }

        $this->info("Dispatched {$count} scheduled report(s).");

        return self::SUCCESS;
    }

    private function generate(ReportSchedule $schedule, array $dataset): string
    {
        $filename = "reports/{$schedule->dataset_key}-{$schedule->id}-".now()->format('Ymd_His').'.'.match ($schedule->format) {
            'excel' => 'xlsx',
            'pdf' => 'pdf',
            default => 'csv',
        };

        match ($schedule->format) {
            'excel' => Excel::store(new AnalyticsDatasetExport($dataset), $filename),
            'pdf' => Storage::put($filename, Pdf::loadView('exports.analytics-dataset-pdf', [
                'dataset' => $dataset,
                'companyName' => $schedule->company?->name ?? 'IOMS',
            ])->output()),
            default => Storage::put($filename, $this->toCsv($dataset)),
        };

        return $filename;
    }

    private function toCsv(array $dataset): string
    {
        $rows = ['Category,Count'];
        foreach ($dataset['labels'] as $i => $label) {
            $rows[] = '"'.str_replace('"', '""', $label).'",'.($dataset['values'][$i] ?? 0);
        }

        return implode("\n", $rows);
    }
}
