<?php

namespace App\Console\Commands;

use App\Exports\AnalyticsDatasetExport;
use App\Models\CompanySetting;
use App\Models\ReportSchedule;
use App\Services\AnalyticsService;
use App\Services\NotificationService;
use App\Support\CurrentTenant;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;

/**
 * Milestone 3 (Report Center, Task #65). Generates every due
 * ReportSchedule's file into storage/app/reports and notifies the
 * owning user through the Notification Center -- deliberately NOT an
 * email dispatcher: scheduled reports were never wired to a Mail
 * transport (see docs/ADR/020-report-center.md), so building an email
 * pipeline here would be exactly the kind of unverifiable "looks done,
 * isn't" feature CLAUDE.md warns against. The notification links back
 * into Report Center, where the same dataset can be re-downloaded live
 * at any time -- the stored file is a point-in-time snapshot, not the
 * only way to get the data.
 */
class DispatchScheduledReports extends Command
{
    protected $signature = 'reports:dispatch-scheduled';

    protected $description = 'Generate every due ReportSchedule and notify its owner.';

    public function handle(AnalyticsService $analytics, NotificationService $notifications): int
    {
        // v2.62.0 -- the ONE query in this command that is deliberately
        // cross-tenant, and it says so.
        //
        // This command is the driver that walks every customer's due
        // schedules and then adopts each one's tenant in turn (see the
        // loop below). It therefore runs BEFORE any tenant exists, where
        // CompanyOwnedScope correctly returns nothing -- so the scope is
        // dropped by name for this statement only. Everything the loop
        // does afterwards runs fully scoped, under the schedule's own
        // tenant.
        //
        // `withoutGlobalScopes()` here is the greppable, reviewable form of
        // "I mean across tenants". A forgotten where-clause is not.
        $due = ReportSchedule::withoutGlobalScopes()
            ->where('is_active', true)
            ->where(function ($q) {
                $q->whereNull('next_run_at')->orWhere('next_run_at', '<=', now());
            })
            ->with(['user', 'tenant'])
            ->get();

        $count = 0;

        $currentTenant = app(CurrentTenant::class);

        foreach ($due as $schedule) {
            if (! $schedule->user) {
                continue;
            }

            // v2.40.0 -- CONFIRMED DEFECT FIXED. This command runs from
            // the scheduler (hourly, see routes/console.php), so there is
            // no HTTP request and therefore no resolved tenant. Every
            // tenant-owned query underneath AnalyticsService goes through
            // `Company::query()`, whose TenantScope fails CLOSED on an
            // unresolved tenant (`tenant_id = -1`). The result was not a
            // leak -- failing closed is the right posture -- but it meant
            // $companyIds came back EMPTY and every scheduled report was
            // generated with zero rows, while the owner was still notified
            // that their report was "ready". An empty report is
            // indistinguishable from "you genuinely had no data", which is
            // the same class of untruth as a green zero on an empty
            // dashboard. It also made `$schedule->company` resolve to null,
            // so every PDF was titled "IOMS" instead of the tenant's own
            // company name.
            //
            // The schedule already knows its owner, so the context is
            // recoverable exactly rather than guessed. Set per iteration
            // (not once outside the loop) because consecutive schedules
            // routinely belong to different tenants.
            if (! $schedule->tenant) {
                $this->warn("Skipping schedule {$schedule->id}: owning tenant is missing.");

                continue;
            }

            $currentTenant->set($schedule->tenant);

            $dataset = $analytics->dataset($schedule->dataset_key);
            $path = $this->generate($schedule, $dataset);

            $notifications->notify(
                $schedule->user,
                \App\Models\Notification::CATEGORY_INFORMATION,
                "Scheduled report ready: {$dataset['label']}",
                'Generated by Report Center ('.$schedule->frequency.', '.$schedule->format.').',
                route('report-center.index'),
                $schedule
            );

            $schedule->update([
                'last_run_at' => now(),
                'next_run_at' => $schedule->computeNextRunAt(),
            ]);

            $count++;
        }

        // Leave no tenant bound once the run is over.
        $currentTenant->set(null);

        $this->info("Dispatched {$count} scheduled report(s).");

        return self::SUCCESS;
    }

    private function generate(ReportSchedule $schedule, array $dataset): string
    {
        $filename = "reports/{$schedule->dataset_key}-{$schedule->id}-".now()->format('Ymd_His').'.'.match ($schedule->format) {
            'excel' => 'xlsx',
            'pdf' => 'pdf',
            default => 'csv',
        };

        match ($schedule->format) {
            'excel' => Excel::store(new AnalyticsDatasetExport($dataset), $filename),
            'pdf' => Storage::put($filename, Pdf::loadView('exports.analytics-dataset-pdf', [
                'dataset' => $dataset,
                'companyName' => $schedule->company?->name ?? CompanySetting::get('company_name', config('ioms.name')),
            ])->output()),
            default => Storage::put($filename, $this->toCsv($dataset)),
        };

        return $filename;
    }

    private function toCsv(array $dataset): string
    {
        $rows = ['Category,Count'];
        foreach ($dataset['labels'] as $i => $label) {
            $rows[] = '"'.str_replace('"', '""', $label).'",'.($dataset['values'][$i] ?? 0);
        }

        return implode("\n", $rows);
    }
}
