<?php

return [

    /*
    |--------------------------------------------------------------------------
    | IOMS Application Configuration
    |--------------------------------------------------------------------------
    |
    | Single source of truth for version/release/developer information
    | shown throughout the UI -- About dialog, sidebar footer, login
    | footer, and the Home page "What's New" banner all read this via the
    | shared Inertia prop (see HandleInertiaRequests::share()). Bump
    | `version` and update `release_date` + `whats_new` together whenever
    | a release ships, and add the previous release to `version_history`.
    | Nothing else in the codebase needs to change.
    |
    */

    'version' => '2.39.0',

    // Tester / Beta / Stable -- tracks the release stage explicitly.
    // Previously only implied in conversation, never actually stored.
    'stage' => 'Beta',

    /*
    |--------------------------------------------------------------------------
    | Canonical Product Identity
    |--------------------------------------------------------------------------
    |
    | v2.38.0. THE single source of truth for what this product is called.
    | Added because a browser audit found the forbidden long-form name
    | ("Integrated Operations Management System") hardcoded as a fallback in
    | TWELVE separate places -- app.jsx, the Inertia shared props, four
    | Excel/PDF export classes, the About dialog, layout tooltips and
    | config/excel.php -- so it silently surfaced in browser titles AND in
    | generated documents whenever a tenant had not set its own company
    | name. IOMS is a standalone product brand, like SAP or Oracle; the
    | expansion is not the product name and must not be used as branding.
    |
    | `descriptor` is the optional positioning line, never a substitute for
    | the name itself.
    |
    */

    'name' => 'IOMS',

    'descriptor' => 'Industrial Operations Platform',

    'edition' => 'Enterprise Edition',

    'build' => '2026.09.05.01',

    'release_date' => '2026-09-05',

    /*
    |--------------------------------------------------------------------------
    | Display timezone
    |--------------------------------------------------------------------------
    |
    | v2.37.0 (Master Audit, P1 -- confirmed defect). `APP_TIMEZONE` is UTC,
    | which is correct for STORAGE and must not change. The bug was in
    | PRESENTATION: the PTW PDF formatted Carbon instances directly
    | (`$permit->start_datetime->format('d M Y H:i')`), printing the raw
    | UTC wall clock, while the React views ran `new Date(iso)
    | .toLocaleString()`, printing the *viewer's browser* timezone. Same
    | instant, two different clock faces -- an exact 8-hour disagreement
    | for a WITA (UTC+8) user, which is precisely the PDF-vs-UI mismatch
    | reported from production.
    |
    | Worse than the mismatch itself: because the web side followed each
    | device, two users in different timezones saw DIFFERENT validity
    | windows for the same Permit to Work. A permit reading
    | "08:37 - 17:00" to one person and "16:37 - 01:00" to another is a
    | materially different safety document.
    |
    | This is the single timezone every human-facing rendering of a stored
    | instant resolves against, so a document reads identically for every
    | viewer regardless of device. Storage stays UTC; only display is
    | pinned. Env-overridable per deployment rather than hardcoded, since
    | IOMS is a standardized multi-tenant product, not one customer's app.
    |
    */
    'display_timezone' => env('IOMS_DISPLAY_TIMEZONE', 'Asia/Jakarta'),

    'developer' => 'Yofhanza Shultona Rizqi S.',

    'company' => 'YSR Systems',

    'copyright_year' => '2026',

    'license' => 'Commercial Enterprise License',

    'website' => 'www.iomsplatform.com',

    'support_email' => 'support@ioms.local',

    'documentation_url' => 'docs.iomsplatform.com',

    'whats_new' => [
        'Public website hero redesigned with a platform visualization showing IOMS connecting HSE, People, Operations, Warehouse, Procurement, Logistics, Projects, and Reports',
        'Pricing plans on the public site now have clearer visual hierarchy and plan framing',
        'Login now includes a show/hide password toggle',
        'Login and password pages share the same premium visual identity as the public website',
    ],

    /*
    |--------------------------------------------------------------------------
    | Version History
    |--------------------------------------------------------------------------
    |
    | Shown on the About page below "What's New" as a scrollable release
    | history. Newest first. Kept intentionally short (a one-line summary
    | per release) -- CHANGELOG.md remains the detailed record.
    |
    */

    'version_history' => [
        ['version' => '2.39.0', 'date' => '2026-09-05', 'summary' => 'Truthful zero states + repository consolidation. Browser-verified on a genuinely empty tenant: the Dashboard congratulated a brand-new customer with "Great job! No critical issues detected today," and HSE Overview rendered six KPI cards reading 0 in the healthy GREEN accent plus "Tidak ada yang terlambat saat ini" -- an all-clear asserted on a database with no employees and no records of any kind. For an HSE platform that is a safety claim nothing supports. Added TenantReadinessService (ONE memoised EXISTS query, no new table, no persisted onboarding state, no wizard -- derived live so it self-corrects), shared as a `readiness` Inertia prop for signed-in tenant users only. DashboardShell gained a single-line qualifying notice, which cascades to all nine department Overviews with zero per-controller wiring. StatCard now encodes "green is a claim": a positive semantic accent downgrades to neutral when no data could have produced it, while amber/red pass through untouched so a real warning is never silently muted. Propagated the honest pattern HSE Man-Hour already used ("--" plus an explicit unavailable reason) rather than inventing a second language for it. Also documented -- with a passing characterisation test -- a confirmed cross-tenant defect in company_settings (see ROADMAP "BLOCKED"); no schema change made. Brand integrity: the forbidden long-form product name removed from CompanySettingSeeder (a fresh install seeded it, and it then reached PDFs, Excel exports and the app shell), README, CHANGELOG and CLAUDE.md.'],
        ['version' => '2.38.0', 'date' => '2026-09-04', 'summary' => 'SaaS foundation (Master Audit P1). SecureDocumentController: authenticated, tenant-checked document delivery driven by a whitelist registry keyed by type + record id, with the path read from the database and never from the URL -- it streams from the new private disk OR the legacy public disk, so it ships with ZERO file migration. Subscription seat limits were previously only ever DISPLAYED, never enforced -- user creation now checks entitlement inside a locking transaction, reusing the exact shape already proven for the PTW quota. EmployeeSelector added as a shared platform primitive: seven controllers were preloading an entire employee directory into the page payload just to render a <select>, unusable at the 1,500-3,000 headcount IOMS targets; it is async, debounced, out-of-order-response guarded, department-grouped and id-hydrating, backed by a tenant-scoped EmployeeLookupController capped at 50 rows. Deliberately NOT built on Combobox (that one is free-text-over-preloaded-strings) and deliberately NOT solved by making pic_name free text, which would have destroyed the ability to answer "which permits was this person responsible for?" -- exactly what an HSE audit asks.'],
        ['version' => '2.37.0', 'date' => '2026-09-03', 'summary' => 'Security + testability (Master Audit P0). Three CONFIRMED cross-tenant defects fixed after auditing all 172 route-model-bound controller methods (163 were already correctly guarded): ProjectController::update never invoked its policy, allowing a cross-tenant WRITE; PpeController and TaskController allowed cross-tenant READS of employee PII, the latter handling a nullable tasks.company_id. Added the reusable InCurrentTenant validation rule, replacing unscoped `exists:` across 17 FormRequests so a submitted foreign id can no longer reference another tenant record; it memoises the tenant company set per rule instance so wildcard rules do not issue one lookup per row. Automated testing was impossible before this release and is now unblocked: phpunit.xml simply did not exist, and six migrations used MySQL-only syntax (MODIFY COLUMN, multi-table UPDATE ... JOIN, information_schema) that no other driver could run -- each is now driver-aware with the MySQL path preserved byte-identical, so production behaviour is unchanged and all 148 migrations provision on SQLite. Also fixed a real PTW timezone defect: the form seeded datetime-local inputs from an ISO/UTC string, the likely root cause of the reported "UI 4:37 PM vs PDF 08:37" mismatch.'],
        ['version' => '2.36.0', 'date' => '2026-09-02', 'summary' => 'Visual System 2.0: a genuine, visible transformation rather than another token-only pass. Added two new design tokens completing the directional palette (navy, steel) to the existing brand/graphite/semantic system -- no parallel color system. Dashboard\'s hero banner rebuilt from a barely-tinted white box into a real deep-navy-to-IOMS-blue "Command Center" surface (white text, an explicit "IOMS · Industrial Operations Platform" eyebrow, filter controls restyled for the dark surface). DashboardShell -- the one shared component every department Overview (HSE, Warehouse, Logistics, Procurement, Project Management, Assets, Maintenance, Quality Control) already composes through -- rebuilt from plain PageHeader into a soft steel/blue "domain summary surface," deliberately lighter than the Dashboard hero so Dashboard-vs-Overview stays visually distinct while both read as part of the same system; every existing caller gets this automatically, no page-level changes needed. Sidebar gained a subtle top-to-bottom tint (was flat white); TopBar gained a faint blue-tinted backdrop. PeriodFilter gained an optional triggerClassName so its selects can be restyled for a dark surface without duplicating the component. No business logic, RBAC, tenant isolation, PTW workflow, or database changes.'],
        ['version' => '2.35.0', 'date' => '2026-09-02', 'summary' => 'Visual System + Information Architecture Refinement: fixed a real reported mobile bottom-nav bug -- visibleNav\'s own "Dashboard" entry was duplicating the hardcoded "Home" tab (both pointing at the same route), and grouped items (e.g. HSE\'s "Permit & Work Safety") were skipped entirely, so PTW could never reach the bar while unrelated top-level items like Waste Management filled the slots instead. Rebuilt the candidate logic to dedupe Dashboard, surface each group\'s first real child (generic, not HSE-specific), and deprioritize Waste Management out of the primary slots per this pass\'s explicit direction -- Waste remains fully reachable via Overview/sidebar/More, only demoted from this one high-frequency bar. Renamed the pinned first slot "Home" -> "Dashboard" (there is no separate Home concept). AuthenticatedLayout\'s background gained a second, bottom-of-viewport tint layer addressing the repeated "too white" production finding -- the v2.29.0 tint only reached the top-left corner of a tall scrolled page. Most of this phase\'s scope (Dashboard vs Overview distinction, HSE Inventory, Digital Checklist, PTW Access, Waste language/workflow, landing page positioning, password visibility) was audited and confirmed already correctly addressed in prior phases (ae83d48 and earlier) -- not re-touched without a confirmed gap. No migrations, no RBAC/tenant-isolation/PTW-workflow/entitlement changes.'],
        ['version' => '2.34.0', 'date' => '2026-09-02', 'summary' => 'Post-Deployment Product Gap pass: audit-first review of six named production concerns found each was either already fully built (just undiscoverable) or genuinely absent. HSE Inventory (APAR/P3K/HT/safety cones) already existed in full under "HSE Master Data" -- relabeled to "Equipment & Master Data" with an explicit subtitle instead of being rebuilt. "Digital Checklist" (a Dashboard/Field Home quick-action label) and the sidebar\'s "Inspection" item were the same hse-inspections feature under two different names -- sidebar relabeled to match. PTW Access management existed only inside Settings > Users with zero sidebar entry point -- added one (same queryParams.tab pattern Administration items already use, no new authorization gate). Legal & Compliance confirmed genuinely absent (broad codebase search for license/regulatory/statutory/compliance found nothing) -- reported as missing, not fabricated. Waste Management\'s remaining English explanatory text (Dashboard/Form/Index/Show subtitles, an EmptyState, a CardDescription) naturalized to Indonesian per the established hybrid-language rule; Waste module/field names stayed English. Confirmed the "HSE-heavy Dashboard" concern in production actually describes Field/Home.jsx (a distinct, intentionally task-first page for the narrow is_department_user account type), not the actual Dashboard/Index.jsx (already cross-domain and already restructured in v2.29.0) -- documented, not conflated. No migrations, no RBAC/tenant-isolation/PTW-workflow/entitlement changes.'],
        ['version' => '2.33.0', 'date' => '2026-09-01', 'summary' => 'Phase 4 (Operational Documents + Waste + Backup/Security Audit): audit-first pass across Document/Waste/Backup/Security/Public Website. Real finding -- Waste Management\'s full generate-to-vendor-handover lifecycle (WasteRecord/WasteMovement/WasteMovementDocument) already existed with a real state machine; only a formal printable manifest was missing, added as waste-movements.pdf reusing the exact same DocumentEngine/PdfGeneratorService pipeline PTW/Material Request already use (no migration, no new PDF engine). Security audit found and fixed three real gaps: login/forgot-password/reset-password routes had no rate limiting (added Laravel\'s built-in throttle:6,1), WasteMovementController\'s document upload had no mimes: whitelist (added, matching every sibling upload validator), and .env.example still shipped the stale full product-name branding (corrected to "IOMS" so a fresh deployment starts correct). Extracted a new shared PasswordInput component and applied it to 7 password fields across Settings and Platform > Tenants that had no show/hide toggle (Login/Reset Password already had one since v2.27.0). Backup architecture audited and found to be a manual, on-demand, same-server-only mysqldump feature with no automation or off-site copy -- documented as a finding, not silently implemented as a false "solved." Public website positioning re-confirmed intact, not rebuilt. No migrations, no RBAC/tenant-isolation/PTW-workflow/entitlement changes.'],
        ['version' => '2.32.0', 'date' => '2026-09-01', 'summary' => 'Interior UI Completion Phase 3B (People, Operations, KPI): Employees Index and Man-Hour/Work Orders desktop tables switched their avatar/identity cells to the shared PersonChip component (brand-tinted, consistent with Employee Profile). Leave, Daily Reports, and Work Orders each gained a mobile identity-first card list (previously relied entirely on horizontal table scroll on narrow viewports), an unboxed filter toolbar, and consolidated desktop columns from 6-7 equal-weight columns down to 3-5 grouped cells -- no data dropped. Man-Hour\'s two summary boxes switched to StatCard (same already-real total_hours/record_count values). KPI Records gained real color-coded category quick-filter chips (each category\'s own admin-configured color, not a fabricated count). No target/trend/achievement percentage was added anywhere in KPI -- confirmed again that no such field exists in the data model. No business logic, RBAC, tenant isolation, database, leave/workflow, or Man-Hour calculation changes.'],
        ['version' => '2.31.0', 'date' => '2026-09-01', 'summary' => 'Interior UI Transformation Phase 3 (People, Operations, Management/KPI, Settings, Micro-interactions): Employee Profile\'s identity block now sits on its own soft-blue tinted header band (brand-tinted avatar, name/code/status) separated from Work Information below, instead of one flat card. KPI Records gained a real primary summary card (total records, semantically accented when a category filter is active) before its table -- no fabricated target/trend, since no target field exists anywhere in the KPI data model (confirmed, not built around). Projects Index cards gained a status-accent bar (planned/ongoing/completed/cancelled), extending StatCard\'s own accent convention into Operations. Settings\' 16-tab wall regrouped into 5 visually separated clusters (Company, Master Data, People & Access, Workflow & Documents, System) -- same tabs, same RBAC gates, grouping only. Reusable micro-interactions added: Button gained real press feedback (motion-safe active:scale), CollapsibleSection\'s expand/collapse switched from an instant pop to the same smooth CSS-grid technique already proven on the sidebar\'s own sub-menus, Settings\' tab active-state gained a transition. No business logic, RBAC, tenant isolation, database, or PTW/A4 document changes.'],
        ['version' => '2.30.0', 'date' => '2026-09-01', 'summary' => 'Interior UI Transformation Phase 2 (Domain Experience): actual domain-page redesigns, not another shared-component-only pass. Reports gained a real visual treatment -- PageHeader, KpiSummaryCard-based key summary (same icon/color-driven cards Dashboard already uses, same KpiCategory data, no fabrication), and department table headers switched from a solid color band to a tinted section-header style. Global Dashboard\'s HeroSummary now shifts its own surface tone (soft blue "all clear" vs soft amber "attention") instead of only a small footer strip. Procurement Dashboard\'s 8 stat cards regrouped into Pipeline / Delivery & Completion / Vendors & Value with eyebrow labels, communicating actual workflow position. Warehouse\'s "Barang Stok Menipis" card gets a real amber-tinted header when low-stock items exist. Logistics\' existing Material Flow pipeline visualization was deliberately preserved (already good, per this pass\'s own instruction) -- only its surrounding surface treatment changed, with the current bottleneck stage (computed from the same real per-stage counts already on screen) getting a stronger visual accent. No business logic, RBAC, tenant isolation, database, or PTW/A4 document changes.'],
        ['version' => '2.29.0', 'date' => '2026-09-01', 'summary' => 'Authenticated UI Visual Transformation: shared-component-first pass, not a page-by-page audit. StatCard gained a real accent color-bar, hover lift, and an opt-in `hint` line -- cascades automatically into every domain dashboard already using it (HR, HSE, Logistics, Maintenance, PPE, Procurement, Project Management, Quality Control, Warehouses, Assets, Corrective Actions, Work Orders, the Global Dashboard). ModuleTabNav\'s active tab now gets a tinted surface instead of a bare underline, plus an optional real-data `meta` count line -- wired live into PPE\'s Employee/Replacement Due/Replacement Requests tabs from each page\'s own already-loaded paginator/array data, never fabricated. AuthenticatedLayout gained a fixed, very-low-opacity blue-tinted background layer (white Cards/Sidebar/TopBar still read as the brighter surface on top). Dashboard gained explicit "Company Snapshot" / "Needs Attention" section labels separating primary state from operational-attention KPIs. MobileBottomNav\'s active tab gained a top indicator bar + tinted icon pill. EmptyState\'s icon chip switched from plain neutral gray to the app\'s own soft-blue surface. No business logic, RBAC, tenant isolation, database, or PTW/A4 document changes -- the A4 density work from 66addf6 is untouched.'],
        ['version' => '2.28.0', 'date' => '2026-09-01', 'summary' => 'Product Experience Transformation, Deliverable B (PTW A4 Document): PTW Document.jsx and pdf/permit-to-work.blade.php redensified for a real A4 print target -- title/section/field/signature spacing roughly halved, Permit Type and PTW Number now share one compact row instead of stacking, keeping every section, field, and data point unchanged (numbered 01-05 information architecture from v2.20.0 untouched). Deliverable A (philosophy correction): the one Enterprise-as-"custom" line on the public Pricing section reworded to reflect IOMS as a standardized SaaS product -- Enterprise as the most complete tier (broader access, capacity, reporting), not bespoke development; is_custom flag, PricingService, and entitlement logic untouched. Broader interior-UI domains (Dashboard/HSE/Warehouse/etc.) re-audited and confirmed already consistent with the shared-component visual language established across v2.15.0-v2.27.0 -- no further change made where none was warranted.'],
        ['version' => '2.27.0', 'date' => '2026-08-31', 'summary' => 'Public Website & Auth Visual Transformation: redesigned Hero with a platform visualization (central IOMS hub + 8 real domain nodes, lg:-only for safe mobile fallback), a distinct English "Built for Industrial Operations" industry statement, and a white -> light-blue -> soft-blue ambient system with subtle motion-safe animation (2 new Tailwind keyframes, no new dependency). Redesigned pricing cards with visual hierarchy (no invented "Most Popular" claim) and plan framing text. Login gained a show/hide password toggle (also added to Reset Password) and the same visual identity as the public site. Public/authenticated app boundary, RBAC, business logic, and pricing data untouched.'],
        ['version' => '2.26.0', 'date' => '2026-08-31', 'summary' => 'Final Copy Consistency Check: naturalized the Dashboard hero subtitle, Material Requests subtitle, and four Warehouse/Item Master page subtitles to Indonesian. Actually inspected (not blindly modified) the PHP flash-message layer -- confirmed the existing ~176 messages are already uniformly clear, professional English; fixed the one genuine inconsistency found (5 messages with a redundant "...successfully." suffix). Logistics Dashboard and navigation labels re-confirmed already correct, left unchanged. Pure copy pass -- no layout, business-logic, or database change. This closes the IOMS UI/UX + copy consistency work.'],
        ['version' => '2.25.0', 'date' => '2026-08-31', 'summary' => 'Global UX & Copywriting Polish: naturalized 18 confirm() dialogs from English "Remove this X?" to consistent Indonesian "Hapus X ini?" across Daily Reports/Employees/HSE Inspection/Leave/Man-Hour/Milestones/PPE/Report Center/RFQ/Settings; added Indonesian explanatory copy to Login/Forgot Password/Reset Password (labels/buttons stay English); Settings Subscription tab copy naturalized; public website hero tagline corrected from a drifted "Industrial Operations Management Platform" back to "Industrial Operations Platform", subheadline naturalized to Indonesian. Pure copy pass -- no layout, component, or business-logic change. PHP-side controller flash messages (176 call sites) not systematically reviewed -- flagged as a follow-up, not silently skipped.'],
        ['version' => '2.24.0', 'date' => '2026-08-31', 'summary' => 'Complete Product UI/UX Transformation, closing the remaining gaps: Purchase Requisition (Purchasing) and KPI Records (Management) got the same identity-first table + mobile card treatment as prior passes; Reports gained a client-side "key summary" strip (no fabricated data) read before the detailed matrices; Logistics Dashboard and Report Center reviewed and found already good (Logistics already has a genuine pipeline visualization, not just cards). Presentation only -- no business logic, RBAC, or database changes.'],
        ['version' => '2.23.0', 'date' => '2026-08-31', 'summary' => 'Complete Product UI/UX Transformation, continued: extended the identity-first list pattern (established on PTW/Incidents) to one representative page per remaining domain -- Safety Observation (HSE), Employees (People/HR), Man-Hour (Operations), Goods Receipt (Warehouse/Procurement) -- each gaining a mobile card list where none existed, consolidated desktop columns, and an unboxed filter bar. Public website hero/platform copy, Dashboard hierarchy, and Settings/Subscription were reviewed and found already adequate -- left unchanged. Presentation only -- no business logic, RBAC, or database changes.'],
        ['version' => '2.22.0', 'date' => '2026-08-31', 'summary' => 'Complete Product UI/UX Transformation pass: new fixed mobile bottom navigation bar (Home + up to 3 authorized items + More, reusing the exact same RBAC/department-filtered nav array and drawer the sidebar already uses -- no second permission system); "IOMS" restored as the primary product name in the browser tab title, app config fallback, and public site footer (was drifting toward the full "Integrated Operations Management System" expansion, and this environment\'s own .env had a stale pre-rebrand "Shipyard Management System" title); Incidents list got the same identity-first table consolidation PTW Index introduced last pass. No business logic, RBAC, tenant isolation, SaaS entitlement, or database changes.'],
        ['version' => '2.21.0', 'date' => '2026-08-31', 'summary' => 'Final Visual Polish pass (P0 scope): PTW Index desktop table consolidated from 9 equal-weight columns to 6 identity-first cells (Permit = number+type, Project/Location, Requester/PIC, each a two-line grouped unit) -- no data dropped, real visual hierarchy instead. Filter bar unboxed from its Card. Presentation only. Broader multi-module polish (Dashboard/HSE/PPE/etc.) intentionally left for a follow-up pass given this pass\'s own P0-first priority and proportionate scope.'],
        ['version' => '2.20.0', 'date' => '2026-08-31', 'summary' => 'PTW Experience & Visual Polish pass: redesigned PTW Document/PDF around a numbered information architecture (01 Work Information -> 05 Supporting Documents) with a dominant document-title block and PIC/Workforce shown via a new reusable PersonChip avatar component instead of plain text; PTW Show page gained a more prominent identity/status header; PTW Create form gained numbered step badges. Presentation only -- no schema, workflow, RBAC, tenant isolation, SaaS entitlement, or quota changes. Same PdfGeneratorService/DocumentEngine pipeline, no new PDF engine.'],
        ['version' => '2.19.0', 'date' => '2026-08-31', 'summary' => 'PTW Access Management Correction pass: fixed settings.users.ptw-access being gated role:super_admin only at the route level -- STRICTER than SettingsController::updatePtwAccess()\'s own canManageHse() check, meaning HSE could never actually reach it despite the controller already allowing it. Moved to its own role:super_admin,hse route group. Settings > Users tab now opens for HSE too, but split into two independent cards -- User Management (create/edit/delete/role changes) stays Super-Admin-only; Field & PTW Access (toggle + quota) opens to HSE. Requester/PIC/Workforce/quota logic re-audited and confirmed already correct, no changes needed. No HSE Dashboard, Field Home, PTW workflow, or database changes.'],
        ['version' => '2.18.0', 'date' => '2026-08-31', 'summary' => 'Public Website / Landing Page Foundation: `/` is now a genuinely public route (previously redirected straight to /login for anyone not signed in) showing a real product website -- hero, platform capabilities, PTW-to-HSE workflow story, Field/HSE/People/Data sections, industries, FAQ, and a Pricing section driven live from Package data (never a hardcoded price). New PublicLayout (separate from AuthenticatedLayout, no sidebar). No customer names/logos/counts/testimonials invented anywhere. Authenticated users hitting `/` are still redirected into the app exactly as before. No RBAC, tenant isolation, PTW workflow, or database changes.'],
        ['version' => '2.17.1', 'date' => '2026-08-31', 'summary' => 'PTW Field Workflow Verification & Correction pass: fixed the max_users(10)/max_ptw_users(15) contradiction on Starter by raising max_users to 15, and PlatformController::validatePlan() now server-enforces max_ptw_users <= max_users for any future Plan edit; PTW Index (HSE workspace) now shows Project/PIC/Workforce headcount on desktop and mobile, via N+1-free eager loading. Re-audited Requester/PIC/Workforce/security -- all confirmed correct, no changes needed there. No HSE Dashboard, Field Home scope, PTW state machine, pricing, billing, or checkout changes.'],
        ['version' => '2.17.0', 'date' => '2026-08-31', 'summary' => 'PTW Field Workflow Foundation + Controlled PTW Access: new per-user "PTW Access" grant (users.ptw_access) lets specific non-HSE Field/Operations users create PTWs, capped by a new package-level PTW user quota (packages.max_ptw_users, server-enforced with race-safe locking); Field Home\'s Create PTW tile now reflects this instead of HSE-role-only; PTW gained optional PIC/Supervisor and Workforce (real Employee references, tenant-scoped) shown consistently on Show/Document/PDF. Requester was already correctly server-derived -- confirmed, not changed. No HSE Dashboard, PTW state machine, RBAC, tenant isolation, or subscription state machine changes.'],
        ['version' => '2.16.0', 'date' => '2026-08-31', 'summary' => 'Global Mobile UX Hardening pass: fixed ModuleTabNav (PPE\'s tab bar) causing page-level horizontal scroll on mobile -- the root cause of a reported PPE screenshot regression -- by containing the scroll to the tab row itself; fixed two PPE list rows (Employees, Replacement Due) whose fixed-width columns exceeded narrow viewports; sidebar drawer now closes explicitly on mobile nav-item tap. Audited broadly (tabs, tables, dialogs, grids, fixed widths) -- most tables were already safely self-scrolling via the shared Table component\'s own wrapper, so no table changes were needed. No business logic, HSE Dashboard, Field Home, PTW workflow, RBAC, tenant isolation, subscription, or database changes.'],
        ['version' => '2.15.0', 'date' => '2026-08-30', 'summary' => 'Product UI/UX Finalization: fixed the dialog component app-wide so tall forms no longer clip off-screen on mobile (max-h + internal scroll + safe margin, previously only one page had opted in); PageHeader now stacks title-above-actions on mobile instead of squeezing both onto one row; added a warning Badge variant so "Overdue"/"High priority" read distinctly from "Rejected"/"Critical"; Incident list converted to the proven PTW mobile-card pattern. Audit-first, shared-components-first pass -- no business logic, dashboard widgets, sidebar structure, or Field Home scope changed.'],
        ['version' => '2.14.0', 'date' => '2026-08-30', 'summary' => 'SaaS Productization / Pricing Foundation: Package confirmed as the canonical Plan entity (currency/trial_days/is_public/is_custom added, no new plans table); new PricingService is the single source of formatted plan pricing (never hardcoded in a component); new tenant-facing Plans comparison page; trial-days-to-trial_ends_at wiring; upgrade/downgrade and billing-ready architecture documented for a later phase. No checkout, payment gateway, or final pricing decision -- explicitly out of scope.'],
        ['version' => '2.13.0', 'date' => '2026-08-30', 'summary' => 'SaaS Phase 1 -- Subscription Architecture & Entitlement Enforcement: server-side per-workspace entitlement enforcement enabled by default (previously built, never wired on); a tenant with no grant rows is now safely treated as fully allowed instead of fully denied, so this cannot lock out a pre-existing tenant; new `tenants:sync-grants` command additively tops up a partially-granted tenant to its Package baseline; entitlement-denied messages now in Bahasa Indonesia. No new table, no payment/billing/pricing/checkout work (explicitly out of scope for this phase).'],
        ['version' => '2.12.0', 'date' => '2026-09-07', 'summary' => 'Product Finalization pass: fixed three real cross-tenant leaks found by a fresh security audit (Material Request full IDOR across 9 controller methods, PPE Replacement Request view/PDF IDOR, KpiRecordController default-state full leak), fixed a hardcoded-branding PDF footer, added two missing delete confirmations, improved the Employees empty state. No database change, no new route.'],
        ['version' => '2.11.0', 'date' => '2026-09-06', 'summary' => 'Field/Foreman Experience pass, Phase 3E-3H: Digital Checklist reworked into one-tap OK/Not OK/N/A cards (no more sideways scrolling), Safety Observation/JSA/HIRADC mobile grid fixes, Incident investigation Recommendations now visible read-only, a real "New LOTO" quick action added (previously had zero entry point). No database change, no new route.'],
        ['version' => '2.10.0', 'date' => '2026-09-05', 'summary' => 'PTW Document Polish pass (Phase 3D): fixed a real PDF/browser-document parity gap (rejection reason was missing from the PDF), HIRADC/JSA now show title/job_title not just the reference number, print output made dark-mode-safe with proper A4 page setup and break-inside protection. No database change, no new route.'],
        ['version' => '2.9.0', 'date' => '2026-09-04', 'summary' => 'Field/Foreman Experience pass (Phase 3C -- My PTW): new requester-scoped, card-based My PTW view (permits-to-work.mine) with real status filter counts and inline Resubmit for rejected permits; Field Home\'s My PTW tile now links here with live pending/active counts. No new table, no new role, no database change.'],
        ['version' => '2.8.0', 'date' => '2026-09-03', 'summary' => 'PTW Mobile / Task-First pass (Phase 3B): mobile card list for PTW Index (status always visible, no horizontal scroll), a real "resubmit" action for rejected permits (the state machine already allowed it, the UI never exposed it), rejection reason surfaced on the Show page, remaining mobile grid fixes.'],
        ['version' => '2.7.0', 'date' => '2026-09-02', 'summary' => 'Field/Foreman Experience pass (Phase 3A): the universal dashboard route now branches to a new task-first Field Home page for Department Users -- large action tiles (Create PTW/My PTW/Checklist/Observation/Incident/My Tasks), reusing existing routes and WorkCenterService counts, no new RBAC, no database change.'],
        ['version' => '2.6.0', 'date' => '2026-09-01', 'summary' => 'PTW Document View pass: new in-browser, printable PTW document presentation (company header, work info, hazards/HIRADC/JSA, gas test, authorization, signatures), reached via a new primary "View PTW Document" action on the PTW detail page; Download PDF unchanged, reusing the existing PdfGeneratorService.'],
        ['version' => '2.5.0', 'date' => '2026-08-31', 'summary' => 'Field HSE Experience pass (Phase 2): CAPA Open/Overdue/In Progress/Closed summary + Overdue filter, Global Search gained HIRADC/JSA, PPE Master vs Operations made visually distinct, mobile-responsive fixes across HSE Inspection/Incident/PPE, natural-Indonesian empty states with primary actions.'],
        ['version' => '2.4.0', 'date' => '2026-08-30', 'summary' => 'PTW UX + Field Operations pass (Phase 1): PTW PDF document generation, Create form progressive disclosure, Submit now reaches Pending Approval in one step, Reject requires a reason, mobile/responsive fixes across the module.'],
        ['version' => '2.3.0', 'date' => '2026-08-29', 'summary' => 'HSE Operations pass: new Waste Container Inventory (physical drum/IBC/jumbo-bag stock, separate from waste material records), Man-Hour 500 fix re-verified, PPE Master Edit audited and confirmed correct, Quick Actions gained a Waste entry.'],
        ['version' => '2.2.0', 'date' => '2026-08-25', 'summary' => 'IOMS OS Ecosystem pass: Man-Hour 500 root-caused and fixed (ambiguous SQL column), Quick Actions and Work Center Action Center extended across every department, Global Search extended (PPE/CAPA/PTW/Assets/Vendors) and its cross-tenant scoping gap fixed, a second cross-tenant leak fixed in Work Center approvals/PPE-alerts, sidebar navigation language reverted to English.'],
        ['version' => '2.1.0', 'date' => '2026-08-25', 'summary' => 'HSE Starter package made genuinely operational: Man-Hour opened to HSE (entitlement-dependency-rule fix), Package-to-Workspace/Module grant mapping wired into tenant creation, PPE Dashboard "+" action fix, optional per-workspace entitlement enforcement (off by default).'],
        ['version' => '2.0.0', 'date' => '2026-08-16', 'summary' => 'Milestone 2: Tenancy Foundation, Platform Super Admin, Package/Subscription structure, RBAC (spatie/laravel-permission), DB-driven Module and Workspace catalogs, Platform Super Admin console.'],
        ['version' => '1.6.10', 'date' => '2026-08-11', 'summary' => 'Material Request complete workflow (HasWorkflow trait); RBAC options evaluated (Spatie Permission recommended, docs/ADR/006); new Warehouse role.'],
        ['version' => '1.6.9', 'date' => '2026-08-09', 'summary' => 'Universal Approval Engine and Activity Timeline viewer -- verified ActivityLog already existed before building anything new.'],
        ['version' => '1.6.8', 'date' => '2026-08-08', 'summary' => 'Employee Import from Excel; Report Export architecture prepared; two severe runtime bugs found and fixed via verification, not assumption.'],
        ['version' => '1.6.7', 'date' => '2026-08-06', 'summary' => 'ModuleTabNav reusable navigation; several desktop density passes; Material Request and PPE Replacement Request MVPs; reusable PdfGeneratorService.'],
        ['version' => '1.6.6', 'date' => '2026-08-03', 'summary' => 'PPE employee-centric restructure; navigation redesign; Browser QA stabilization (white flash, Select bug sweep).'],
        ['version' => '1.6.5', 'date' => '2026-08-02', 'summary' => 'About Dialog rebuilt from scratch; sidebar branding hierarchy fixed; six shared foundation components.'],
        ['version' => '1.6.4', 'date' => '2026-08-01', 'summary' => 'Universal Task Engine foundation; QA stabilization pass across Dashboard, Sidebar, Dark Mode.'],
        ['version' => '1.6.3', 'date' => '2026-07-28', 'summary' => 'Dashboard/Sidebar/TopNav/Theme/Company Branding usability pass; real Global Search; Forgot/Reset Password.'],
        ['version' => '1.6.2', 'date' => '2026-07-27', 'summary' => 'Root-cause fix for watermark clipping; exact 240px/70px/16px/24px branding specs; searchable Combobox.'],
        ['version' => '1.6.1', 'date' => '2026-07-26', 'summary' => 'Fixed a real PHP parse error; Dashboard Today\'s Summary; Top Department Workload; About fields expanded.'],
        ['version' => '1.6.0', 'date' => '2026-07-25', 'summary' => 'Enterprise UI refresh: centralized config/ioms.php, About dialog scrolling fixed, branding sizing pass.'],
    ],

];
