import { useRef, useState } from 'react';
import {
    LayoutDashboard, ShieldCheck, Users, FolderKanban, PackageSearch, ShoppingCart,
    Building2, AlertTriangle, ClipboardCheck, Boxes, Flame, Eye,
    GraduationCap, Flag, PackageCheck, FileStack, FileQuestion,
    Clock, HardHat, Search, Bell, ChevronDown,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * v2.59.0 -- THE PRODUCT SHOWCASE, AND WHY IT REPLACED WHAT WAS HERE.
 *
 * The landing page's "What working in IOMS looks like" section rendered
 * two panels. One was an HSE dashboard whose four figures were literally
 * the character "—" above a dashed empty rectangle; the other was a permit
 * with three grey bars where its content should be. A visitor evaluating
 * industrial software saw placeholder furniture and no product. Both
 * panels were also HSE/PTW, so the entire product visualisation on a page
 * selling an Industrial Operations Platform showed one department.
 *
 * v2.61.0 -- WHICH WORKSPACES, AND HOW FAITHFUL THE NUMBERS ARE.
 *
 * The five tabs were Dashboard, HSE, Warehouse, Procurement, Maintenance.
 * Two problems with that set:
 *
 *   WAREHOUSE IS A SHELL. `warehouse` in the workspace registry is a
 *   Dashboard and an Overview. Everything the old Warehouse tab showed --
 *   item master, stock levels, goods receipt -- actually lives under
 *   LOGISTICS / PPIC. The tab was showing a real capability under the
 *   wrong workspace name, which is the one kind of inaccuracy a product
 *   showcase cannot afford. Renamed to the workspace that owns it.
 *
 *   PEOPLE AND PROJECTS WERE ABSENT. Human Resources and Project
 *   Management are two of the four departments the plan ladder is built
 *   on, and neither appeared. A visitor comparing tiers could not see
 *   what Professional or Business actually adds.
 *
 * The six tabs are now Dashboard, HSE, Human Resources, Project
 * Management, Logistics / PPIC and Procurement -- which is also exactly
 * the ladder: HSE at Starter, People at Professional, the other three at
 * Business.
 *
 * EVERY STAT LABEL IS THE REAL ONE. These are not invented KPI names:
 * they are the labels the actual department dashboards render (see
 * Pages/Hse/Dashboard.jsx, Pages/Hr/Dashboard.jsx,
 * Pages/ProjectManagement/Dashboard.jsx, Pages/Logistics/Dashboard.jsx,
 * Pages/Procurement/Dashboard.jsx), given in English because this page is
 * English. The FIGURES are illustrative sample data and the section says
 * so in its own subtitle.
 *
 * EVERY DOCUMENT NUMBER FOLLOWS THE REAL NUMBERING SCHEME. PTW, INC,
 * CAPA, MR, PR, PO, GRN, PRJ -- generated by NumberGeneratorService in
 * the application, not invented for this page.
 *
 * INTERACTION. A tab switch: instant, no autoplay, nothing moving while a
 * visitor is reading. Arrow keys move between tabs and Home/End jump to
 * the ends, which is what a tablist is expected to do and what the
 * previous version did not implement.
 */

const MODULES = [
    {
        key: 'dashboard',
        label: 'Dashboard',
        icon: LayoutDashboard,
        eyebrow: 'Management',
        title: 'Dashboard',
        subtitle: 'Operational summary across every department and Operating Unit.',
        stats: [
            { icon: Users, value: '248', label: 'Active Workforce' },
            { icon: FolderKanban, value: '12', label: 'Active Projects', accent: 'green' },
            { icon: Building2, value: '2', label: 'Operating Units' },
        ],
        attention: [
            { icon: AlertTriangle, value: '3', label: 'Open Incidents', accent: 'red' },
            { icon: ClipboardCheck, value: '7', label: 'Open CAPA', accent: 'amber' },
            { icon: ShoppingCart, value: '5', label: 'Pending PO Approval', accent: 'purple' },
            { icon: Boxes, value: '9', label: 'Low Stock Items', accent: 'amber' },
        ],
        rows: [
            ['Man-hours this month', '38,420'],
            ['Days since last LTI', '164'],
            ['Documents generated', '1,208'],
        ],
    },
    {
        key: 'hse',
        label: 'Health, Safety & Environment',
        icon: ShieldCheck,
        eyebrow: 'Department',
        title: 'Health, Safety & Environment',
        subtitle: 'Permit To Work, incidents, observations, inspections and corrective actions.',
        stats: [
            { icon: Flame, value: '6', label: 'Active Permits', accent: 'green' },
            { icon: AlertTriangle, value: '3', label: 'Open Incidents', accent: 'red' },
            { icon: Eye, value: '4', label: 'Open Observations', accent: 'amber' },
        ],
        table: {
            head: ['Number', 'Work', 'Status'],
            rows: [
                ['PTW-2026-00184', 'Hot work — shell plate, Dock 2', 'Active'],
                ['PTW-2026-00183', 'Confined space — ballast tank 3P', 'Approved'],
                ['INC-2026-00021', 'Near miss — dropped object', 'Investigation'],
                ['CAPA-2026-00044', 'Scaffold inspection frequency', 'In progress'],
            ],
        },
    },
    {
        key: 'hr',
        label: 'Human Resources',
        icon: Users,
        eyebrow: 'Department',
        title: 'Human Resources',
        subtitle: 'Employees, competency, shifts and rosters, leave and man-hour.',
        stats: [
            { icon: Users, value: '248', label: 'Active Employees' },
            { icon: HardHat, value: '186', label: 'On Duty Today', accent: 'green' },
            { icon: GraduationCap, value: '5', label: 'Certifications Expiring', accent: 'amber' },
        ],
        table: {
            head: ['Employee', 'Record', 'Status'],
            rows: [
                ['Welding Supervisor — Dock 2', 'Annual leave, 3 days', 'Submitted'],
                ['Rigger — Fabrication Shop', 'Rigging certificate, 21 days left', 'Expiring'],
                ['Night shift roster — Week 38', '42 assigned', 'Published'],
                ['Contract renewal — 4 employees', 'Ends in 30 days', 'Review'],
            ],
        },
    },
    {
        key: 'project-management',
        label: 'Project Management',
        icon: FolderKanban,
        eyebrow: 'Department',
        title: 'Project Management',
        subtitle: 'Projects, milestones, manpower assignment and daily reports.',
        stats: [
            { icon: FolderKanban, value: '12', label: 'Active Projects' },
            { icon: Flag, value: '78%', label: 'Milestone Completion', accent: 'green' },
            { icon: AlertTriangle, value: '2', label: 'Delayed Projects', accent: 'red' },
        ],
        table: {
            head: ['Project', 'Milestone', 'Status'],
            rows: [
                ['PRJ-2026-0114 — Tanker drydocking', 'Hull blasting complete', 'In progress'],
                ['PRJ-2026-0109 — Barge fabrication', 'Block assembly 4 of 6', 'In progress'],
                ['DR-2026-00312 — Daily report', '38 manpower, Dock 2', 'Submitted'],
                ['PRJ-2026-0098 — Crane overhaul', 'Load test', 'Delayed'],
            ],
        },
    },
    {
        key: 'logistics',
        label: 'Logistics / PPIC',
        icon: PackageSearch,
        eyebrow: 'Department',
        title: 'Logistics / PPIC',
        subtitle: 'Material requests, item master, inventory, goods receipt and stock movement.',
        stats: [
            { icon: PackageSearch, value: '8', label: 'Pending Material Requests', accent: 'amber' },
            { icon: Boxes, value: '1,340', label: 'Item Master' },
            { icon: PackageCheck, value: '24', label: 'Received This Month', accent: 'green' },
        ],
        table: {
            head: ['Item', 'On hand', 'Status'],
            rows: [
                ['Welding Electrode E7018 3.2mm', '18 box', 'Low stock'],
                ['Steel Plate A36 10mm', '64 sheet', 'In stock'],
                ['Safety Harness Full Body', '11 pcs', 'Low stock'],
                ['GRN-2026-00097 — received', '40 box', 'Posted'],
            ],
        },
    },
    {
        key: 'procurement',
        label: 'Procurement',
        icon: ShoppingCart,
        eyebrow: 'Department',
        title: 'Procurement',
        subtitle: 'Requisitions, RFQ and vendor comparison, purchase orders and vendors.',
        stats: [
            { icon: FileStack, value: '5', label: 'Pending PRs', accent: 'amber' },
            { icon: FileQuestion, value: '3', label: 'Open RFQs' },
            { icon: Clock, value: '9d', label: 'Avg. Purchase Cycle', accent: 'green' },
        ],
        table: {
            head: ['Document', 'Vendor', 'Status'],
            rows: [
                ['PR-2026-00051', 'Awaiting evaluation', 'Submitted'],
                ['PO-2026-00042', 'PT Baja Sentosa Nusantara', 'Issued'],
                ['PO-2026-00041', 'CV Anugerah Teknik Marine', 'Delivered'],
                ['MR-2026-00126', 'Raised by Logistics / PPIC', 'Approved'],
            ],
        },
    },
];

const ACCENTS = {
    red: 'bg-gradient-to-br from-danger to-red-600',
    amber: 'bg-gradient-to-br from-warning to-amber-600',
    green: 'bg-gradient-to-br from-success to-emerald-700',
    purple: 'bg-gradient-to-br from-violet-500 to-violet-700',
    default: 'bg-gradient-to-br from-navy-800 to-brand-600',
};

// Status colouring mirrors StatusBadge's own vocabulary: waiting states
// are amber, done states green, problems red, everything else neutral.
const STATUS_TONES = {
    Active: 'bg-success/10 text-success',
    Approved: 'bg-success/10 text-success',
    Posted: 'bg-success/10 text-success',
    Published: 'bg-success/10 text-success',
    Delivered: 'bg-success/10 text-success',
    'In stock': 'bg-success/10 text-success',
    Submitted: 'bg-warning/10 text-amber-700',
    Expiring: 'bg-warning/10 text-amber-700',
    Review: 'bg-warning/10 text-amber-700',
    'Low stock': 'bg-warning/10 text-amber-700',
    Investigation: 'bg-danger/10 text-danger',
    Delayed: 'bg-danger/10 text-danger',
    'In progress': 'bg-brand-50 text-brand-700',
    Issued: 'bg-brand-50 text-brand-700',
};

export default function PlatformShowcase() {
    const [active, setActive] = useState(MODULES[0].key);
    const tabRefs = useRef({});
    const module = MODULES.find((m) => m.key === active) ?? MODULES[0];

    // Arrow-key navigation, per the tablist pattern. The previous version
    // was a row of buttons with role="tab" and no key handling, which is
    // the shape of the pattern without the behaviour it promises.
    const onKeyDown = (event) => {
        const order = MODULES.map((m) => m.key);
        const current = order.indexOf(active);
        let next = null;

        if (event.key === 'ArrowRight' || event.key === 'ArrowDown') next = (current + 1) % order.length;
        if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') next = (current - 1 + order.length) % order.length;
        if (event.key === 'Home') next = 0;
        if (event.key === 'End') next = order.length - 1;
        if (next === null) return;

        event.preventDefault();
        setActive(order[next]);
        tabRefs.current[order[next]]?.focus();
    };

    return (
        <div>
            {/* Workspace switcher. Mirrors the department selector pattern
                the application itself uses, so the control is recognisable
                before a visitor has ever signed in. */}
            <div
                className="-mx-4 flex gap-2 overflow-x-auto px-4 pb-2 sm:mx-0 sm:flex-wrap sm:px-0"
                role="tablist"
                aria-label="IOMS workspaces"
                onKeyDown={onKeyDown}
            >
                {MODULES.map((m) => {
                    const isActive = m.key === active;

                    return (
                        <button
                            key={m.key}
                            ref={(el) => { tabRefs.current[m.key] = el; }}
                            type="button"
                            role="tab"
                            id={`showcase-tab-${m.key}`}
                            aria-selected={isActive}
                            aria-controls={`showcase-panel-${m.key}`}
                            tabIndex={isActive ? 0 : -1}
                            onClick={() => setActive(m.key)}
                            className={cn(
                                'flex shrink-0 items-center gap-1.5 rounded-full border px-3.5 py-1.5 text-xs font-medium transition-all',
                                'focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 focus-visible:ring-offset-2',
                                isActive
                                    ? 'border-navy-900 bg-navy-900 text-white shadow-card'
                                    : 'border-graphite-200 bg-white text-graphite-600 hover:border-graphite-300 hover:text-graphite-900'
                            )}
                        >
                            <m.icon className="h-3.5 w-3.5" />
                            {m.label}
                        </button>
                    );
                })}
            </div>

            {/* The application frame. */}
            <div className="mt-4 overflow-hidden rounded-xl border border-graphite-200 bg-white shadow-lift">
                {/* v2.61.0: an application chrome bar. The product has a
                    top bar with an Operating Unit selector, search and
                    notifications on every page; without it the panel below
                    read as a slide rather than as software. Inert by
                    design -- it is a picture of the toolbar, so it carries
                    no controls a visitor could try to use. */}
                <div
                    className="flex items-center gap-3 border-b border-graphite-200 bg-graphite-50 px-3 py-2"
                    aria-hidden="true"
                >
                    <div className="flex items-center gap-1.5">
                        <span className="h-2.5 w-2.5 rounded-full bg-graphite-300" />
                        <span className="h-2.5 w-2.5 rounded-full bg-graphite-300" />
                        <span className="h-2.5 w-2.5 rounded-full bg-graphite-300" />
                    </div>
                    <div className="flex min-w-0 flex-1 items-center gap-1.5 rounded-md border border-graphite-200 bg-white px-2 py-1">
                        <Building2 className="h-3 w-3 shrink-0 text-graphite-400" />
                        <span className="truncate text-[10px] font-medium text-graphite-600">Batam Yard — Operating Unit</span>
                        <ChevronDown className="ml-auto h-3 w-3 shrink-0 text-graphite-400" />
                    </div>
                    <Search className="hidden h-3.5 w-3.5 shrink-0 text-graphite-400 sm:block" />
                    <Bell className="hidden h-3.5 w-3.5 shrink-0 text-graphite-400 sm:block" />
                </div>

                <div className="flex">
                    {/* Navigation rail -- the product's own navy, collapsed to
                        icons because the tabs above already name the modules. */}
                    <div className="hidden w-14 shrink-0 flex-col items-center gap-1 bg-navy-900 py-4 sm:flex" aria-hidden="true">
                        {MODULES.map((m) => (
                            <span
                                key={m.key}
                                className={cn(
                                    'flex h-9 w-9 items-center justify-center rounded-lg transition-colors',
                                    m.key === active ? 'bg-white/[0.14] text-white' : 'text-navy-300'
                                )}
                            >
                                <m.icon className="h-4 w-4" />
                            </span>
                        ))}
                    </div>

                    <div className="min-w-0 flex-1">
                        {/* Page header band -- the same navy header the real
                            Dashboard carries, eyebrow and all. */}
                        <div className="bg-gradient-to-r from-navy-900 to-navy-800 px-4 py-3.5 sm:px-5">
                            <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-steel-300">
                                IOMS · {module.eyebrow}
                            </p>
                            <p className="mt-0.5 text-sm font-semibold tracking-tight text-white">{module.title}</p>
                            <p className="mt-0.5 text-[11px] text-navy-300">{module.subtitle}</p>
                        </div>

                        {/* `key={active}` remounts on switch so the existing
                            `fade-in` token replays -- reusing the design
                            system's own keyframe rather than inventing a
                            second one. Wrapped in motion-safe, like every
                            other animation in this codebase. */}
                        <div
                            key={active}
                            id={`showcase-panel-${active}`}
                            role="tabpanel"
                            aria-labelledby={`showcase-tab-${active}`}
                            tabIndex={0}
                            className="space-y-3 p-4 focus:outline-none motion-safe:animate-fade-in sm:p-5"
                        >
                            <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-3">
                                {module.stats.map((s) => <Chip key={s.label} {...s} />)}
                            </div>

                            {module.attention && (
                                <>
                                    <p className="pt-1 text-[10px] font-semibold uppercase tracking-wide text-graphite-400">
                                        Needs Attention
                                    </p>
                                    <div className="grid grid-cols-2 gap-2.5 sm:grid-cols-4">
                                        {module.attention.map((s) => <Chip key={s.label} {...s} />)}
                                    </div>
                                </>
                            )}

                            {module.rows && (
                                <dl className="divide-y divide-graphite-100 rounded-lg border border-graphite-100">
                                    {module.rows.map(([label, value]) => (
                                        <div key={label} className="flex items-center justify-between px-3 py-2">
                                            <dt className="text-xs text-graphite-500">{label}</dt>
                                            <dd className="text-xs font-semibold text-navy-900">{value}</dd>
                                        </div>
                                    ))}
                                </dl>
                            )}

                            {module.table && (
                                <div className="overflow-x-auto rounded-lg border border-graphite-100">
                                    <table className="w-full min-w-[420px]">
                                        <thead>
                                            <tr className="bg-graphite-50">
                                                {module.table.head.map((h) => (
                                                    <th key={h} className="px-3 py-2 text-left text-[10px] font-semibold uppercase tracking-wide text-graphite-400">
                                                        {h}
                                                    </th>
                                                ))}
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-graphite-100">
                                            {module.table.rows.map((row) => (
                                                <tr key={row[0]} className="transition-colors hover:bg-graphite-50/70">
                                                    <td className="whitespace-nowrap px-3 py-2 text-[11px] font-medium text-navy-900">{row[0]}</td>
                                                    <td className="px-3 py-2 text-[11px] text-graphite-600">{row[1]}</td>
                                                    <td className="whitespace-nowrap px-3 py-2">
                                                        <span
                                                            className={cn(
                                                                'rounded-full px-1.5 py-0.5 text-[10px] font-semibold',
                                                                STATUS_TONES[row[2]] ?? 'bg-graphite-100 text-graphite-600'
                                                            )}
                                                        >
                                                            {row[2]}
                                                        </span>
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>

            <p className="mt-3 text-xs leading-relaxed text-graphite-500">
                Every workspace above ships in IOMS today. Figures are illustrative sample data; the modules,
                document numbering and statuses are the real ones. Which workspaces a customer sees depends on
                their plan.
            </p>
        </div>
    );
}

function Chip({ icon: Icon, value, label, accent }) {
    return (
        <div className="flex items-center gap-2.5 rounded-lg border border-graphite-100 bg-white p-2.5 transition-shadow hover:shadow-card">
            <span className={cn('flex h-7 w-7 shrink-0 items-center justify-center rounded-[9px] text-white', ACCENTS[accent] ?? ACCENTS.default)}>
                <Icon className="h-[15px] w-[15px]" />
            </span>
            <span className="min-w-0">
                <span className="block text-base font-semibold leading-tight text-navy-900">{value}</span>
                <span className="block truncate text-[10px] font-medium uppercase tracking-wide text-graphite-400">{label}</span>
            </span>
        </div>
    );
}
